# Generated by Django 2.2.6 on 2019-12-12 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentStatus', models.CharField(max_length=50)),
                ('PayTime', models.DateTimeField()),
                ('RecordTime', models.DateTimeField()),
                ('TrackingCode', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Username', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageContent', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SalesMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Username', models.CharField(max_length=50)),
                ('ActivityDescription', models.TextField()),
                ('ActivityFields', models.CharField(max_length=300)),
                ('Approved', models.BooleanField()),
                ('Email', models.EmailField(max_length=254)),
                ('IdentificationImage', models.TextField()),
                ('Location', models.CharField(max_length=300)),
                ('Name', models.CharField(max_length=300)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('ProfileImage', models.TextField()),
                ('RegistrationTime', models.DateTimeField()),
                ('Suspend', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=300)),
                ('Color', models.CharField(max_length=50)),
                ('Count', models.IntegerField()),
                ('Description', models.TextField()),
                ('isStock', models.BooleanField(default=False)),
                ('Name', models.CharField(max_length=300)),
                ('Price', models.IntegerField()),
                ('RecordTime', models.DateTimeField()),
                ('SalesMan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.SalesMan')),
            ],
        ),
        migrations.CreateModel(
            name='BasketProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.IntegerField()),
                ('State', models.CharField(max_length=50)),
                ('Basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Basket')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Costumer'),
        ),
    ]
