# Generated by Django 2.2.6 on 2019-12-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'costumer'},
        ),
        migrations.AlterField(
            model_name='basketproduct',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='imageContent',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='identificationImage',
            field=models.ImageField(blank=True, null=True, upload_to='salesman_identification_image'),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='salesman_profile'),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='suspend',
            field=models.BooleanField(default=False),
        ),
    ]
